### ISSUE TITLE
-bash: /root/gopath/src/goterm: No such file or directory

### ISSUE THREAD

**Issue by Mountains-and-rivers** [freman/goterm#2]
when i run "$GOPATH/bin/goterm -assets `pwd`", i got an error ：

-bash: /root/gopath/bin/goterm: No such file or directory

my path is：

export GOROOT=/opt/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=~/gopath

[root@izbp12kmrje8amdruhsx4sz github.com]# ls
goterm
[root@izbp12kmrje8amdruhsx4sz github.com]# 
[root@izbp12kmrje8amdruhsx4sz github.com]# cd goterm/
[root@izbp12kmrje8amdruhsx4sz goterm]# pwd
/root/gopath/src/github.com/goterm
[root@izbp12kmrje8amdruhsx4sz goterm]# 

why run $GOPATH/bin/goterm -assets `pwd`？

**Comment by freman** [comment]
Those instructions are based on the assumption that go has built and installed goterm in $GOPATH/bin which is the relatively standard place for it to end up

If you've built it in some other path, then... that's where your binary is and that's what you have to run.

**Comment by Mountains-and-rivers** [comment]
> Those instructions are based on the assumption that go has built and installed goterm in $GOPATH/bin which is the relatively standard place for it to end up
> 
> If you've built it in some other path, then... that's where your binary is and that's what you have to run.

OK thanks!
